# c_cipher.py
# This module contains a function to process an email string by shifting its characters up by 3 in the ASCII table.
# It validates the input email for length and alphanumeric content.

def cipher_email(email):
    """
    Processes an email string by shifting each character up by 3 in the ASCII table.

    Parameters:
    email (str): The email string to be processed. It must be exactly 6 characters long
                 and contain only alphanumeric characters.

    Returns:
    str or None: The processed email string if validation is successful; otherwise, None.
    
    Raises:
    ValueError: If the input email does not meet the required criteria.
    """
    
    # Input validation
    if len(email) != 6:
        print("Error: Email length must be exactly 6 characters.")
        return None
    if not email.isalnum():
        print("Error: Email must be alphanumeric.")
        return None

    # Process the string
    email_list = list(email)  # Convert string to list of characters
    shifted_list = []

    for char in email_list:
        shifted_char = chr(ord(char) + 3)  # Shift character up by 3 in ASCII
        shifted_list.append(shifted_char)  # Append the shifted character to the new list

    retVal = ''.join(shifted_list)  # Convert the list back to a string
    return retVal

# Example usage
if __name__ == "__main__":
    email_input = input("Enter an email (6 characters, alphanumeric): ")
    result = cipher_email(email_input)
    if result:
        print(f"Shifted email: {result}")

  
