# c_cipher.py
# This module contains functions for encrypting and decrypting alphanumeric strings.

def encrypt(email):
    """
    Encrypts a given alphanumeric email by shifting each character's ASCII value up by 3.
    
    Args:
        email (str): The email string to be encrypted. Must be exactly 6 characters long and alphanumeric.

    Returns:
        str or None: The encrypted email if valid, otherwise None with an error message.
    """
    # Input validation
    if len(email) != 6:
        print("Error: Email length must be exactly 6 characters.")
        return None
    
    if not email.isalnum():
        print("Error: Email must be alphanumeric.")
        return None
    
    # Process the string
    char_list = list(email)
    for i in range(len(char_list)):
        char_list[i] = chr(ord(char_list[i]) + 3)
    
    return ''.join(char_list)


def decrypt(email):
    """
    Decrypts a given alphanumeric email by shifting each character's ASCII value down by 3.
    
    Args:
        email (str): The email string to be decrypted. Must be exactly 6 characters long and alphanumeric.

    Returns:
        str or None: The decrypted email if valid, otherwise None with an error message.
    """
    # Input validation
    if len(email) != 6:
        print("Error: Email length must be exactly 6 characters.")
        return None
    
    if not email.isalnum():
        print("Error: Email must be alphanumeric.")
        return None
    
    # Process the string
    char_list = list(email)
    for i in range(len(char_list)):
        char_list[i] = chr(ord(char_list[i]) - 3)
    
    return ''.join(char_list)

# Example usage
if __name__ == "__main__":
    email_input = input("Enter the email to encrypt (6 characters): ")
    encrypted = encrypt(email_input)
    if encrypted:
        print(f"Encrypted email: {encrypted}")
        decrypted = decrypt(encrypted)
        print(f"Decrypted email: {decrypted}")

  
